#!/usr/bin/env python3

import rtems_waf.rtems as rtems
import rtems_waf.rootfs as rootfs
import tools.waftools as wt
import subprocess
import cexp

version = "1.0.0"

def init(ctx):
    rtems.init(ctx, version="7", long_commands=True)

def options(opt):
    rtems.options(opt)

    opt.add_option(
        '--cexp-text-section',
        default='auto',
        help='Defines the size of the Cexpsh text section. Setting to "auto" allows it to be determined per BSP. Otherwise must be a number in bytes.'
    )

    opt.add_option(
        '--cexp-loader',
        default='bfd',
        choices=['bfd', 'rtl', 'none'],
        help='Determine the loader to use.',
    )

    opt.add_option(
        '--enable-cexp',
        default=True,
        help='Enable Cexpsh integration'
    )
    
    opt.add_option(
        '--enable-lua',
        default=True,
        help='Enable LUA integration'
    )

def bsp_configure(conf, arch_bsp):
    use_cexp = conf.env.RTEMS_ARCH in ['powerpc', 'i386', 'm68k', 'arm'] and conf.options.enable_cexp
    conf.env.HAVE_CEXP = use_cexp

    # GCC thinks we're not running in a tty
    conf.env.CPPFLAGS += ['-fdiagnostics-color=always']

    rtems.check(conf, 'RTEMS_LIBBSD')
    
    # Check networking stack(s)
    conf.env.NET_NAME = 'none'
    if wt.check_net_stack(conf, 'networking', 'legacy'):
        conf.env.DEFINES += ['RTEMS_LEGACY_STACK=1']
    if wt.check_net_stack(conf, 'bsd', 'bsd'):
        if 'RTEMS_LEGACY_STACK=1' in conf.env.DEFINES:
            conf.error('Multiple networking stacks detected!')
        conf.env.DEFINES += ['RTEMS_BSD_STACK=1']

    conf.env.INCLUDES += [f'{conf.path}/build/{conf.env.RTEMS_ARCH_BSP}']

    if use_cexp:
        conf.env.DEFINES += ['HAVE_CEXP=1']
        conf.env.INCLUDES += ['modules/cexp']

    if conf.options.enable_lua:
        # Enable LUA
        conf.env.DEFINES += ['HAVE_LUA=1']
        conf.env.INCLUDES += ['modules/lua']

    conf.env.HAVE_LUA = conf.options.enable_lua

    wt.report_feature(conf, 'Lua scripting', conf.options.enable_lua)
    wt.report_feature(conf, 'Cexp shell', use_cexp)

    # Feature checks for common headers
    wt.check_include(conf, "rtems.h", "HAVE_RTEMS_H")
    wt.check_include(conf, "sys/mman.h", "HAVE_SYS_MMAN_H")
    wt.check_include(conf, "strings.h", "HAVE_STRINGS_H")
    wt.check_include(conf, "sys/select.h", "HAVE_SYS_SELECT_H")
    wt.check_include(conf, "sys/termios.h", "HAVE_SYS_TERMIOS_H")
    wt.check_include(conf, "termios.h", "HAVE_TERMIOS_H")
    wt.check_include(conf, "ncurses/term.h", "HAVE_NCURSES_TERM_H")
    wt.check_include(conf, "ncurses/curses.h", "HAVE_NCURSES_CURSES_H")
    wt.check_include(conf, "sys/features.h", "HAVE_SYS_FEATURES_H")
    wt.check_include(conf, "link.h", "HAVE_LINK_H")
    wt.check_include(conf, "pthread.h", "HAVE_PTHREADS")
    wt.check_include(conf, "rtems/rtems/cache.h", "HAVE_RTEMS_CACHE_H")
    wt.check_include(conf, "rtems/bsd/bsd.h", "HAVE_BSD_NETWORKING")
    wt.check_include(conf, "rtems/bsdnet/servers.h", "HAVE_LEGACY_NETWORKING")
    wt.check_lib(conf, "debugger", "rtems_debugger_start", "HAVE_DEBUGGER")
    wt.check_lib(conf, "rtemsbsp", "BSP_pci_configuration", "HAVE_PCI")
    #wt.write_config_h(conf, 'config.h.in') # Have to do this in the build step???

def configure(conf):
    rtems.configure(conf, bsp_configure)

def generate_config_header(bld):
    wt.write_config_h(bld, 'config.h.in')


def build(bld):
    rtems.build(bld)

    # Generate the config header now...
    bld.add_pre_fun(generate_config_header)

    # This needs to be done here because it doesn't work in configure for some reason.
    bld.env.INCLUDES += [f'{bld.out_dir}/{bld.env.RTEMS_ARCH_BSP}']

    # Add a rootfs
    rootfs = wt.add_rootfs(bld, 'rootfs', 'rootfs.S')

    if bld.env.HAVE_CEXP:
        cexp.build_cexp(bld)

    bld.add_group()

    includes = [
        'src',
        f'build/{bld.env.RTEMS_ARCH_BSP}',
        '.',
    ]

    source = [
        'src/init.c',
        'src/cexp-text-region.c',
        'src/hack.c',
        'src/net.c',
        'src/nvram.c',
        'src/rtems-config.c',
        'src/rtems-lua.c',
        'src/shell-tools.c',
        'src/shell.c',
        'src/common/getopt_s.c',
        'src/common/util.c',
        'src/test/tests.c',
        'src/test/nfs-perf.c',
        'rootfs.S', # Generated by add_rootfs
    ]
    
    libs = []

    # Generic network related libraries
    if bld.env.NET_NAME != 'none':
        libs += [
            'ntp',
            'tftpfs',
            'ttcp',
            'telnetd',
        ]

    use = []

    if bld.env.HAVE_CEXP:
        use += ['cexp']

    if bld.env.HAVE_LUA:
        source += ['modules/lua/onelua.c']

    if bld.env.NET_NAME == 'bsd':
        source += ['src/net-bsd.c']
        libs += ['bsd']
    elif bld.env.NET_NAME == 'legacy':
        source += ['src/net-legacy.c']
        libs += ['networking']

    libs += [
        'c',
        'm',
        'rtemsbsp',
        'rtemscpu'
    ]

    # Main application
    bld (
        features    = 'c cprogram boot',
        target      = 'rtems-init.exe',
        includes    = includes,
        cflags      = bld.env.CFLAGS,
        defines     = [],
        source      = source,
        use         = use,
        lib         = libs,
    )
