clientid rtems-client
vendorclassid udhcp-rtems
nodhcp6
ipv4only
define 129 string rtems_cmdline
option ntp_servers
option rtems_cmdline
option tftp_server_name
option bootfile
option host_name
option filename
option domain_name
option domain_name_servers
option posix_timezone
timeout 0