tos minclock 3 maxclock 6
restrict default limited kod nomodify notrap noquery nopeer
restrict source  limited kod nomodify notrap noquery
restrict 10.0.0.0 mask 255.0.0.0
restrict 172.16.0.0 mask 255.240.0.0
restrict 192.168.0.0 mask 255.255.0.0
restrict 127.0.0.1
restrict ::1
leapfile "/etc/leap-seconds"